# Azure Pipeline to run tests, generate Allure report, and publish to GitHub Pages

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  GITHUB_TOKEN: $(github_token) # Define in Pipeline > Variables (as secret)

steps:

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean test'
      options: '-DskipTests=false'
    displayName: 'Run Tests'

  - script: |
      mvn io.qameta.allure:allure-maven:report
      mkdir -p gh-pages
      cp -r target/site/allure-maven-plugin/* gh-pages/
    displayName: 'Generate Allure HTML Report'

  - script: |
      cd gh-pages
      git init
      git config user.name "Chinta Anusha"
      git config user.email "chintaanusha@ril.com"  # Replace with your GitHub email
      git remote add origin https://$(GITHUB_TOKEN)@github.com/ChintaAnushha/OspreySearchAJIOAutomation.git
      git checkout -b gh-pages
      git add .
      git commit -m "Publishing Allure report"
      git push origin gh-pages --force
    displayName: 'Publish Allure Report to GitHub Pages'
